---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: centos-6-chef-11
    driver:
      box: bento/centos-6.7
    provisioner:
      require_chef_omnibus: 11.18
  - name: centos-6.7
  - name: centos-7.2
  - name: fedora-22
  - name: fedora-23

suites:
  - name: default
    run_list:
      - recipe[selinux_policy_test::setup]
      - recipe[selinux_policy_test::single_port]
      - recipe[selinux_policy_test::twice_port]
      - recipe[selinux_policy_test::range_port]
      - recipe[selinux_policy_test::bad_port]
      - recipe[selinux_policy_test::module]
      - recipe[selinux_policy_test::module_directory]
      - recipe[selinux_policy_test::fcontext]
      - recipe[selinux_policy_test::fcontext_filetype]
